name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php main.php
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config credential.helper store
          git add -A
          git commit -m "Automatic update"
          git push
